# Description： 公众号：Python自动化办公社区
# Attention： 更多Python学习资源：https://mp.weixin.qq.com/s/sO6hbVqORy7JpN-5TlaKvQ
import turtle as t

t.pensize(10)
t.pencolor("black")
t.circle(100)
t.penup()
t.goto(150,0)
t.pendown()
t.pencolor("red")
t.circle(100)
t.left(180)
t.penup()
t.goto(-150,0)
t.left(180)
t.pendown()
t.pencolor("blue")
t.circle(100)
t.left(90)
t.penup()
t.goto(0,0)
t.pendown()
t.pencolor ("yellow")
t.circle(100)
t.right(180)
t.pencolor("green")
t.circle(100)
t.speed(0)